# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180429_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
