# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180429_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='start',
        ),
    ]
