# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180430_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, ' Bar Mitzvah'), (3, 'Dinner'), (4, 'Vort')]),
        ),
    ]
