# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180430_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
