# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Catering'), (2, 'Music'), (3, 'Photography'), (4, 'Hairdressing'), (5, 'Makeup')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Hall'), (3, 'Other')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wedding'), (2, 'Bar Mitzvah'), (3, 'Dinner'), (4, 'Vort')]),
        ),
    ]
