# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180507_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.AddField(
            model_name='venue',
            name='color',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
