# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180603_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default='2018-06-03 16:00:25'),
            preserve_default=False,
        ),
    ]
